name: hiltonSample
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter_spinkit: ^3.1.0
#  flutter_facebook_login: ^3.0.0
  json_annotation: ^2.0.0
  shimmer: ^1.1.2
  dotted_border: ^1.0.7
  dropdownfield: ^1.0.0
  flutter_staggered_animations: ^0.1.3
  google_sign_in: ^4.5.9
  dio: ^3.0.10
  flutter_html: ^0.11.1
  toast: 0.1.5
  carousel_slider: ^4.0.0
  audioplayers:
  shared_preferences:
  flutter_rating_bar: 3.0.1+1
  image_picker: ^0.6.7+11
  flutter_math: ^0.2.1
  flutter_launcher_icons: "^0.7.0"
  flutter_automation: ^1.3.3
  cached_network_image: ^2.3.2+1
  provider:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.flutter_webview_plugin
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  built_value_generator: ^6.7.1
  flutter_test:
    sdk: flutter
  # Your other dev_dependencies here

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/itgn_app_icon.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - i18n/en.json
    - i18n/sourceList.json
    - assets/images/f_logo.png
    - assets/images/itgn.png
    - assets/images/itgn_app_icon.png


 
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 500



